version: '3.3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=Barcos
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
